hadd hist_GluGluHToTauTauM125_0Jets.root hist_*_GluGluHToTauTauM125_0Jets.root
hadd hist_GluGluHToTauTauM125_2Jets.root hist_*_GluGluHToTauTauM125_2Jets.root
hadd hist_GluGluHToTauTauM125_1JetNotBoosted.root hist_*_GluGluHToTauTauM125_1JetNotBoosted.root
hadd hist_GluGluHToTauTauM125_1JetBoosted.root hist_*_GluGluHToTauTauM125_1JetBoosted.root
hadd hist_GluGluHToTauTauM125_inclusive.root hist_*_GluGluHToTauTauM125_inclusive.root
hadd hist_VBFHToTauTauM125_0Jets.root hist_*_VBFHToTauTauM125_0Jets.root
hadd hist_VBFHToTauTauM125_2Jets.root hist_*_VBFHToTauTauM125_2Jets.root
hadd hist_VBFHToTauTauM125_1JetNotBoosted.root hist_*_VBFHToTauTauM125_1JetNotBoosted.root
hadd hist_VBFHToTauTauM125_1JetBoosted.root hist_*_VBFHToTauTauM125_1JetBoosted.root
hadd hist_VBFHToTauTauM125_inclusive.root hist_*_VBFHToTauTauM125_inclusive.root
hadd hist_DYJetsToLLM50_0Jets.root hist_*_DYJetsToLLM50_0Jets.root
hadd hist_DYJetsToLLM50_2Jets.root hist_*_DYJetsToLLM50_2Jets.root
hadd hist_DYJetsToLLM50_1JetNotBoosted.root hist_*_DYJetsToLLM50_1JetNotBoosted.root
hadd hist_DYJetsToLLM50_1JetBoosted.root hist_*_DYJetsToLLM50_1JetBoosted.root
hadd hist_DYJetsToLLM50_inclusive.root hist_*_DYJetsToLLM50_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM90_inclusive.root hist_*_SUSYGluGluToHToTauTauM90_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM200_inclusive.root hist_*_SUSYGluGluToHToTauTauM200_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM300_inclusive.root hist_*_SUSYGluGluToHToTauTauM300_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM500_inclusive.root hist_*_SUSYGluGluToHToTauTauM500_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM800_inclusive.root hist_*_SUSYGluGluToHToTauTauM800_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM1200_inclusive.root hist_*_SUSYGluGluToHToTauTauM1200_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM1800_inclusive.root hist_*_SUSYGluGluToHToTauTauM1800_inclusive.root
hadd hist_SUSYGluGluToHToTauTauM2600_inclusive.root hist_*_SUSYGluGluToHToTauTauM2600_inclusive.root
hadd hist_HToTauTauM125_0Jets.root hist_GluGluHToTauTauM125_0Jets.root hist_VBFHToTauTauM125_0Jets.root
hadd hist_HToTauTauM125_2Jets.root hist_GluGluHToTauTauM125_2Jets.root hist_VBFHToTauTauM125_2Jets.root
hadd hist_HToTauTauM125_1JetNotBoosted.root hist_GluGluHToTauTauM125_1JetNotBoosted.root hist_VBFHToTauTauM125_1JetNotBoosted.root
hadd hist_HToTauTauM125_1JetBoosted.root hist_GluGluHToTauTauM125_1JetBoosted.root hist_VBFHToTauTauM125_1JetBoosted.root
hadd hist_HToTauTauM125_inclusive.root hist_GluGluHToTauTauM125_inclusive.root hist_VBFHToTauTauM125_inclusive.root
hadd hist_ZprimeToTauTauM2500_inclusive.root hist_*_ZprimeToTauTauM2500_inclusive.root

