#!/bin/bash

dir=(hadhad muhad emu)
genOpt=(gen smeared)

for i in ${dir[*]}; do
  rm -rf $i
  mkdir $i
  for j in ${genOpt[*]}; do
    mkdir $i/$j
  done  
done

for sample in ${dir[*]}; do 
  for option in ${genOpt[*]}; do 
    for i in {0..200}; do 
      sed "s+JOB_ID+$i+g" template_addMassVariables_${sample}_${option}_cfg.py> ${sample}/${option}/addMassVariables_${sample}_${option}_${i}_cfg.py 
    done
  done  
done  


