#!/bin/bash

dir=(hadhad muhad emu)
genOpt=(gen smeared)

for i in ${dir[*]}; do
  rm -rf $i
  mkdir $i
  for j in ${genOpt[*]}; do
    mkdir $i/$j
  done  
done

F=/tmp/prlist
grep -v ^$ $1 > $F
N=`wc $F|awk '{print $1}'`

for i in `seq $N`; do
  DSET=`head -$i $F|tail -1|awk '{print $1}'`
  SN=`head -$i $F|tail -1|awk '{print $2}'`
  echo "sample: $SN"
  for sample in ${dir[*]}; do 
    for option in ${genOpt[*]}; do 
      for job in {0..200}; do 
        echo "channel: $sample, option: $option, job: $job"

        sed "s+DSET+$DSET+g;s+SN+$SN+g;s+DIR+$sample+g;s+OPTION+$option+g;s+JOBID+$job+g" template_mc.cfg > ${sample}/${option}/c_${SN}_${option}_${job}.cfg

      done
    done  
  done  
done

